/*
* This Java source file was generated by the Gradle 'init' task.
*/
package ticket_service;


import ticket_service.cli.EventCli;
import ticket_service.cli.ReservationCli;
import ticket_service.cli.SeatCli;

import java.util.Scanner;

public class App {
  private static SeatCli seatCli = new SeatCli();
  private static EventCli eventCli = new EventCli();
  private static ReservationCli reservationCli = new ReservationCli();

  public static void main(String[] args) {
    listenToCommands();

  }

  private static void listenToCommands(){
    Scanner scanner = new Scanner(System.in);
    while(true) {
      String command = scanner.nextLine();
      executeCommand(command);
    }
  }

  private static void executeCommand(String command) {
    String[] commandFragments = command.split("\\s+");

    switch (commandFragments[0]) {
      case "seat":
        seatCli.execute(commandFragments);
        break;
      case "event":
        eventCli.execute(commandFragments);
        break;
      case "reservation":
        reservationCli.execute(commandFragments);
        break;

      default:
        printCommandNotFound();
    }
  }

  public static void printCommandNotFound(){
    System.out.println("Command not found");
  }

}
